package declarations

var NopBranch ExecutableInstruction
var NopInteger ExecutableInstruction
var NopMemory ExecutableInstruction
var IntegerStoreRegister ExecutableInstruction
var IntegerLoadNoBaseUpdateForm ExecutableInstruction
var BranchIndirectReturn ExecutableInstruction
var AddlImm22 ExecutableInstruction
var AddsImm14 ExecutableInstruction

var IntegerCompareRegisterForm ExecutableInstruction
